[project]
name = "web2-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.2",
    "libsql>=0.1.11",
    "markupsafe>=3.0.2",
    "python-multipart>=0.0.20",
    "uvicorn>=0.36.0",
    "webtypy>=0.1.7",
]

[dependency-groups]
dev = ["workers-py>=1.1.7"]
